version: "3.5"
# You should be able to find & replace all instances of fail2ban with 
# your actual_service_name. Then you just need address any places that 
# typically need changes (designated by comments)

networks:
  fail2ban:

volumes:
  fail2ban:

services:
  ingress:
    networks:
      - fail2ban

  fail2ban:
    environment:
      - TZ=${TZ}
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=1d
      - F2B_MAX_RETRY=3
      - F2B_ACTION=%(action_)s
    deploy:
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    image: ${image_provider:-scififarms}/technocore-fail2ban:${TAG:-latest}
    #<<: *logging-defaults
    networks:
      - fail2ban
    volumes:
      - fail2ban:/data
      - /var/log:/var/log:ro
      - /var/lib/docker/containers/:/var/lib/docker/containers:ro
